version: 1
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y/%m/%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        level: DEBUG
        stream: ext://sys.stdout
    file_cassandra_storage_debug:
        class : logging.FileHandler
        formatter: simple
        level: DEBUG
        filename: '/home/marcus/Python_Projects/cassandra-storage/logs/cassandra_storage_debug.log'
    file_cassandra_storage_info:
        class : logging.FileHandler
        formatter: simple
        level: INFO
        filename: '/home/marcus/Python_Projects/cassandra-storage/logs/cassandra_storage_info.log'
loggers:
    cassandra_storage_debug:
        level: DEBUG
        handlers: [console, file_cassandra_storage_debug]
    cassandra_storage_info:
        level: INFO
        handlers: [console, file_cassandra_storage_info]
root:
    handlers: [console]
    level: NOTSET
